apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: furby-apps
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 1m0s
  path: "./infra/k8s"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
