// Purpose: global runtime configuration

export const config = {
  DISCORD_TOKEN: process.env.DISCORD_TOKEN!,
  DISCORD_APPLICATION_ID: process.env.DISCORD_APPLICATION_ID!,
  DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID!,

  PERSONAL_GOOGLE_SHEET_ID: process.env.PERSONAL_GOOGLE_SHEET_ID!,
  COLABORATIF_GOOGLE_SHEET_ID: process.env.COLABORATIF_GOOGLE_SHEET_ID!,
  GOOGLE_SERVICE_ACCOUNT_KEY: process.env.GOOGLE_SERVICE_ACCOUNT_KEY!,
};
